// Decompiled by:       Fernflower v0.8.6
// Date:                11.08.2012 10:25:07
// Copyright:           2008-2012, Stiver
// Home page:           http://www.neshkov.com/ac_decompiler.html

package com.coa.lnf;

public enum COALnFColors
{
  CONTAINER_OUTER_BORDER, CONTAINER_INNER_BORDER, TITLE_BAR_BACKGROUND, TITLE_BAR_TEXT, HEADER_BACKGROUND, HEADER_TEXT, MENU_BAR_BACKGROUND, MENU_BAR_TEXT, MAIN_BACKGROUND, MAIN_TEXT, BUTTON_ENABLED_BACKGROUND, BUTTON_ENABLED_TEXT, BUTTON_ENABLED_BORDER, BUTTON_DISABLED_BACKGROUND, BUTTON_DISABLED_BORDER, BUTTON_DISABLED_TEXT, BUTTON_SELECTED_BACKGROUND, BUTTON_SELECTED_TEXT, BUTTON_SELECTED_BORDER, BUTTON_ROLLOVER_BACKGROUND, BUTTON_ROLLOVER_TEXT, BUTTON_ROLLOVER_BORDER, FIELD_ENABLED_BACKGROUND, FIELD_ENABLED_TEXT, FIELD_ENABLED_BORDER, FIELD_DISABLED_BACKGROUND, FIELD_DISABLED_BORDER, FIELD_DISABLED_TEXT, FIELD_SELECTED_BACKGROUND, FIELD_SELECTED_TEXT, FIELD_SELECTED_BORDER, LABEL_TEXT, TAB_BACKGROUND, TAB_TEXT, TAB_BORDER, TAB_SELECTED_BACKGROUND, TAB_SELECTED_TEXT, TAB_SELECTED_BORDER, TAB_ROLLOVER_BACKGROUND, TAB_ROLLOVER_TEXT, TAB_ROLLOVER_BORDER, SEPARATOR, DIFFERENTIATED_BACKGROUND, DIFFERENTIATED_BORDER, COLUMN_HEADER, ROW_HIGHLIGHT_1, ROW_HIGHLIGHT_2, ROW_HIGHLIGHT_SELECTED;
}

/* Location:           /home/oracle/coa/cp.ear/cp.ear_orginal/coalnf.jar
 * Qualified Name:     com.coa.lnf.COALnFColors
 * JD-Core Version:    0.6.0
 */