// Decompiled by:       Fernflower v0.8.6
// Date:                12.08.2012 13:04:19
// Copyright:           2008-2012, Stiver
// Home page:           http://www.neshkov.com/ac_decompiler.html

package com.cedar.cp.api.model;

import java.io.Serializable;

public interface ReviewBudgetCellValue extends Serializable {

   int PROTECTION_OFF = 0;
   int PROTECTION_SHEET_NON_LEAF = 1;
   int PROTECTION_SHEET_DISABLED = 2;
   int PROTECTION_SHEET_NON_PLANNABLE = 3;
   int PROTECTION_SHEET_NON_PREPARING = 4;
   int PROTECTION_SHEET_RA_READONLY = 5;
   int PROTECTION_SHEET_RANGECODE = 6;
   int PROTECTION_FORM_TREE_NON_LEAF = 7;
   int PROTECTION_FORM_TREE_DISABLED = 8;
   int PROTECTION_FORM_TREE_NON_PLANNABLE = 9;
   int PROTECTION_FORM_TREE_NON_PREPARING = 10;
   int PROTECTION_NON_LEAF = 11;
   int PROTECTION_DISABLED_ELEMENT = 12;
   int PROTECTION_NON_PLANNABLE_ELEMENT = 13;
   int PROTECTION_CELL_CALC_SUMMARY_MISMATCH = 14;
   int PROTECTION_COLUMN_PROTECTED = 15;
   int PROTECTION_COLUMN_NO_PERSIST = 16;
   int PROTECTION_READONLY_DATATYPE = 17;
   int PROTECTION_PRIOR_BUDGET_CYCLE_PERIOD = 18;
   int PROTECTION_SHEET_BUSINESS_RANGECODE = 19;
   int PROTECTION_INVALID_CALENDAR_REFERENCE = 20;
   int PROTECTION_ELEMENT_NON_PREPARING = 21;
   int PROTECTION_ELEMENT_CUBE_FORMULA_TARGET = 22;

}
