package com.cedar.cp.api.base;

import java.util.Map;
import java.util.Set;
import com.cedar.cp.api.logon.AuthenticationResult;
import com.cedar.cp.api.user.UserRef;

public interface UserContext {

   int BUDGET_INSTRUCTIONS_PROCESS = 3;
   int CELL_CALCULATIONS_PROCESS = 6;
   int NAVIGATOR_PROCESS = 7;
   int CALENDAR_PROCESS = 8;
   int ACCOUNT_DIMENSIONS_PROCESS = 9;
   int BUSINESS_DIMENSIONS_PROCESS = 10;
   int CALENDAR_DIMENSIONS_PROCESS = 11;
   int FINANCE_CUBES_PROCESS = 12;
   int BUDGET_LOCATIONS_PROCESS = 15;
   int BUDGET_CYCLES_PROCESS = 16;
   int BUDGET_USERS_PROCESS = 17;
   int CURRENCYS_PROCESS = 18;
   int DATA_TYPES_PROCESS = 19;
   int MODELS_PROCESS = 20;
   int TASK_MONITORS_PROCESS = 21;
   int LOCK_MONITOR_PROCESS = 22;
   int USER_MONITOR_PROCESS = 23;
   int SQL_MONITORS_PROCESS = 24;
   int RESPONSIBILITY_AREAS_PROCESS = 25;
   int TASK_SCHEDULER_PROCESS = 26;
   int USERS_PROCESS = 27;
   int CONTRIBUTOR_PROCESS = 32;
   int RESPONSIBILITY_AREAS_POWER_INPUT = 35;
   int IMPORT_PROCESS = 36;
   int PREFERENCES_PROCESS = 37;
   int CONTRIBUTOR_RUNTIME_PROCESS = 38;
   int EVENT_PROCESS = 39;
   int ACCOUNT_HIERARCHIES_PROCESS = 40;
   int BUSINESS_HIERARCHIES_PROCESS = 41;
   int CALENDAR_HIERARCHIES_PROCESS = 42;
   int SYSTEM_PROPERTIES_PROCESS = 43;
   int XMLFORM_PROCESS = 44;
   int TABLE_FORM_PROCESS = 45;
   int FIXEDROW_FORM_PROCESS = 46;
   int DYN_FORM_PROCESS = 47;
   int FINANCE_FORM_PROCESS = 48;
   int FLATFORM_FORM_PROCESS = 49;
   int SECURITY_GROUP_PROCESS = 50;
   int SECURITY_ACCESS_PROCESS = 51;
   int SECURITY_RANGE_PROCESS = 52;
   int DATAENTRY_PROCESS = 53;
   int CHANGE_MGMT_PROCESS = 54;
   int IMP_EXP_HDR_PROCESS = 55;
   int PERFORMANCE_PROCESS = 56;
   int XMLREPORT_PROCESS = 58;
   int REPORT_PROCESS = 60;
   int VIREMENT_CATEGORY_PROCESS = 61;
   int PERF_TESTS_PROCESS = 62;
   int PERF_TEST_RUNS_PROCESS = 63;
   int PERF_TEST_RUN_RESULTS_PROCESS = 64;
   int BUDGET_LIMIT_PROCESS = 65;
   int MESSAGE_PROCESS = 66;
   int XMLREPORT_FOLDER_PROCESS = 67;
   int VIREMENT_PROCESS = 68;
   int RECHARGE_PROCESS = 69;
   int RECHARGE_GROUP_PROCESS = 70;
   int ROLES_PROCESS = 71;
   int DATA_ENTRY_PROFILE_PROCESS = 72;
   int VIREMENT_REQUESTS = 73;
   int REPORT_TYPES = 74;
   int REPORT_DEFINITIONS = 75;
   int REPORT_TEMPLATES = 76;
   int EXTERNAL_USERS = 77;
   int INTERNAL_USERS = 78;
   int DISTRIBUTION = 79;
   int REPORT_PACK = 80;
   int WEIGHTING_PROFILE_PROCESS = 81;
   int WEIGHTING_DEPLOYMENT_PROCESS = 82;
   int TIDY_TASK = 83;
   int REPORT_MAPPING_TEMPLATES = 84;
   int MODEL_MAPPING_PROCESS = 85;
   int EXTERNAL_SYSTEM_PROCESS = 86;
   int EXTENDED_ATTACHMENT_PROCESS = 87;
   int E5_DB2_PUSH_PROCESS = 88;
   int UDEF_LOOKUPTABLE_PROCESS = 89;
   int CC_DEPLOYMENT_PROCESS = 90;
   int AMM_MODEL_PROCESS = 91;
   int AUTHENTICATION_POLICY_PROCESS = 92;
   int LOGON_HISTORY = 93;
   int PASSWORD_HISTORY = 94;
   int TASK_GROUP_PROCESS = 95;
   int FORM_REBUILD_PROCESS = 96;
   int CUBE_FORMULA_PROCESS = 97;
   int MASS_VIREMENT_XML_FORM_PROCESS = 98;
   int XCELL_FORM_PROCESS = 99;
   int GLOBAL_MODEL_MAPPING2_PROCESS = 100;
   int USER_MODEL_SECURITY_PROCESS = 101;
   int MASTER_QUESTIONS_PROCESS = 102;
   int CHALLENGE_QUESTIONS_PROCESS = 103;
   int USER_RESET_LINKS_PROCESS = 104;
   int RECALCULATE_BATCH_PROCESS = 105;
   int LOGGED_IN_USERS_PROCESS = 106;
   int NOTES_PROCESS = 107;
   int DATA_EDITOR_PROCESS = 108;
   int CONVERT_XLS_TO_JSON_TASK = 109;
   
   int MAX_PROCESS_ID = 110;
   String[] sProcessSecurityPrefixes = new String[]{"GROUP_ALLOCATIONS_PROCESS", "POWER_ALLOCATIONS_PROCESS", "LOG_FILE_PROCESS", "BUDGET_INSTRUCTIONS_PROCESS", "BASIC_FORMULAE_PROCESS", "POWER_FORMULAE_PROCESS", "CELL_CALCULATIONS_PROCESS", "NAVIGATOR_PROCESS", "CALENDAR_PROCESS", "ACCOUNTS_PROCESS", "BUSINESS_DIMENSIONS_PROCESS", "CALENDARS_PROCESS", "FINANCE_CUBES_PROCESS", "spare", "spare", "BUDGET_LOCATIONS_PROCESS", "BUDGET_CYCLES_PROCESS", "BUDGET_USERS_PROCESS", "CURRENCYS_PROCESS", "DATA_TYPES_PROCESS", "MODELS_PROCESS", "TASK_MONITORS_PROCESS", "LOCK_MONITOR_PROCESS", "USER_MONITOR_PROCESS", "SQL_MONITORS_PROCESS", "RESPONSIBILITY_AREAS_PROCESS", "TASK_SCHEDULER_PROCESS", "USERS_PROCESS", "VISIBILITY_PROFILES_PROCESS", "WORKFLOW_STATUS_PROCESS", "WORKFLOW_TEMPLATES_PROCESS", "WORKFLOW_VIEWER_PROCESS", "CONTRIBUTOR_PROCESS", "GROUP_ALLOCATION_TARGETS_PROCESS", "GROUP_ALLOCATION_SOURCES_PROCESS", "RESPONSIBILITY_AREAS_POWER_INPUT", "IMPORT", "PREFERENCES_PROCESS", "CONTRIBUTOR_RUNTIME_PROCESS", "EVENT_PROCESS", "ACCOUNT_HIERARCHIES_PROCESS", "BUSINESS_HIERARCHIES_PROCESS", "CALENDAR_HIERARCHIES_PROCESS", "SYSTEM_PROPERTIES_PROCESS", "XMLFORM_PROCESS", "TABLE_FORM_PROCESS", "FIXEDROW_FORM_PROCESS", "DYN_FORM_PROCESS", "FINANCE_FORM_PROCESS", "FLATFORM_FORM_PROCESS", "SECURITY_GROUP_PROCESS", "SECURITY_ACCESS_PROCESS", "SECURITY_RANGE_PROCESS", "DATAENTRY_PROCESS", "CHANGE_MGMT_PROCESS", "IMP_EXP_HDR_PROCESS", "PERFORMANCE_PROCESS", "LOOKUPTABLE_PROCESS", "XMLREPORT_PROCESS", "LOOKUPTABLE_PARENT_PROCESS", "REPORT_PROCESS", "VIREMENT_CATEGORY_PROCESS", "PERF_TESTS_PROCESS", "PERF_TEST_RUNS_PROCESS", "PERF_TEST_RUN_RESULTS_PROCESS", "BUDGET_LIMIT_PROCESS", "MESSAGE_PROCESS", "XMLREPORT_FOLDER_PROCESS", "VIREMENT_PROCESS", "RECHARGE_PROCESS", "RECHARGE_GROUP_PROCESS", "ROLES_PROCESS", "DATA_ENTRY_PROFILE_PROCESS", "VIREMENT_REQUESTS", "REPORT_TYPES_PROCESS", "REPORT_DEFINITIONS_PROCESS", "REPORT_TEMPLATES_PROCESS", "EXTERNAL_USERS_PROCESS", "INTERNAL_USERS_PROCESS", "DISTRIBUTION_PROCESS", "REPORT_PACK_PROCESS", "WEIGHTING_PROFILE_PROCESS", "WEIGHTING_DEPLOYMENT_PROCESS", "TIDY_TASK_PROCESS", "REPORT_MAPPING_TEMPLATES_PROCESS", "MODEL_MAPPING_PROCESS", "EXTERNAL_SYSTEM_PROCESS", "EXTENDED_ATTACHMENT_PROCESS", "E5_DB2_PUSH_PROCESS", "UDEF_LOOKUPTABLE_PROCESS", "CC_DEPLOYMENT_PROCESS", "AMM_MODEL_PROCESS", "AUTHENTICATION_POLICY_PROCESS", "LOGON_HISTORY", "PASSWORD_HISTORY", "TASK_GROUP_PROCESS", "FORM_REBUILD_PROCESS", "CUBE_FORMULA_PROCESS", "MASS_VIREMENT_XML_FORM_PROCESS", "XCELL_FORM_PROCESS", "GLOBAL_MODEL_MAPPING2_PROCESS", "USER_MODEL_SECURITY_PROCESS", "MASTER_QUESTIONS_PROCESS", "CHALLENGE_QUESTIONS_PROCESS", "USER_RESET_LINKS_PROCESS", "RECALCULATE_BATCH_PROCESS", "LOGGED_IN_USERS_PROCESS", "NOTES_PROCESS", "DATA_EDITOR_PROCESS", "CONVERT_XLS_TO_JSON_TASK"};
   String SYSTEM_ADMINISTRATOR_ROLE_VIS_ID = "SystemAdministrator";
   String BUDGET_CONTROLLER_ROLE_VIS_ID = "BudgetController";
   String BUDGET_APPROVER_ROLE_VIS_ID = "BudgetApprover";
   String BUDGET_HOLDER_ROLE_VIS_ID = "BudgetHolder";


   CPConnection getConnection();

   String getSystemName();

   Object getPrimaryKey();

   String getLogonId();

   UserRef getUserRef();

   int getUserId();

   String getUserName();

   String getPassword();

   int[] getAllowedBusinessProcesses();

   boolean userMustChangePassword();

   boolean userCanChangePassword();

   int getPasswordExpiryDays();

   int getConnectionResult();

   int getMinimumPasswordSize();

   String getLogonString();

   Set<String> getUserRoles();

   Set<String> getUserRoleSecurityStrings(String var1);

   Map<String, String> getRoleDescriptions();

   boolean hasSecurity(int var1, String var2);

   boolean hasSecurity(String var1);

   boolean isAdmin();

   AuthenticationResult getAuthenticationResult();

   Map getUserPreferenceValues();

   void setUserPreferenceValues(Map var1);

   boolean isNewFeaturesEnabled();
   
   boolean areButtonsVisible();
   
   boolean getRoadMapAvailable();
   
   boolean isShowBudgetActivity();
   
   boolean isNewView();
}
